language: node_js
node_js:
- "10"

cache:
  yarn: true
  directories:
  - "node_modules"

branches:
  only:
  - master

install:
- yarn install

script:
- echo "skipping tests"

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: feedbag-stats-frontend
  on:
    branch: master
